### ISSUE TITLE
Driver UbuntuOne Server

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#2]
We should have a basic driver for the UbuntuOne server.

Work is in progress by @Scylardor . The REST API don't support bulk-download, so it's  not compatible with the current Onitu API. We are trying to use the internal API of UbuntuOne's clients, but the code is quite cryptic.

If anyone is willing to help @Scylardor to understand the code (Python + Twisted + Protobuf + DBus) please comment this issue.

**Comment by Scylardor** [comment]
Well let's do a quick summary of what has been done so far :
- U1's REST API doesn't support partial upload nor notifications upon changes on remote files because developers don't want to implement any non-standard feature in it, so we can't use it
- while the DBus API provides a lot of functionality, it seems to be rather useful for monitoring purposes (i.e. get all the current down/uploads, retrieve metadatas, know when a down/upload finishes...). It doesn't seem to be made for managing transfers as precisely as we want (downloading X bytes at offset Y of the file Z...).
- so we are currently planning to use the internal API of the U1 official client. It isn't very well documented, there's A LOT of code and pretty everything uses Twisted deferred code, which makes it hard to read and understand. For the basic features we need, Twisted is a big dependency and it would be clearly overkill to reuse 'as-is' the ubuntuone-client classes, so we're studying the ubuntuone-storage-protocol in order to make a basic client at least able to do what we want with the U1 file system servers. Also, clients connected in this way are supposed to be notified by the server on every modification of the file system, so it may solve our change notifications problems too. I didn't have time yet to work further on it, but I managed to connect and communicate a bit with the U1 server in this way, so I'm confident that this will probably work. 

The U1 developers however told us that it wasn't a very good idea to develop a client using ubuntuone-storage-protocol now, as it doesn't really fit with Ubuntu's direction development's planning. I still think that for today, it is what fits our needs best. The internal protocol is indeed implemented with Google Protocol Buffers, and pretty well understood now, so I think it's just a matter of time. Any help is appreciated.

**Comment by k4nar** [comment]
I removed it from the 0.1 Milestone, as @Scylardor would like to have more time to work on this.

**Comment by Khady** [comment]
[Canonical is shutting down U1](http://blog.canonical.com/2014/04/02/shutting-down-ubuntu-one-file-services/). I think that we can close this issue and forget U1.

**Comment by k4nar** [comment]
Yep, I agree. The file-sync service will shut down in the next few month, so it doesn't worth it.
