### ISSUE TITLE
Driver Dropbox

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#3]
We should have a basic driver for Dropbox. @Akiat started working on it with, then @manny42 agreed to be in charge.

@manny42 : Did you make any progress ?

**Comment by k4nar** [comment]
Any news on that @manny42 ?

**Comment by manny42** [comment]
So the news are, I have trouble on making the request, I keep getting 403, so I try to fix this issue.

**Comment by k4nar** [comment]
It might be a problem with your OAuth token, check you credentials.

**Comment by manny42** [comment]
Credential are okay but I think it's the way I send them, I always run a check for credential first

**Comment by k4nar** [comment]
Do you use the last version of the Dropbox API ? There is a fresh release : https://pypi.python.org/pypi/dropbox

**Comment by manny42** [comment]
I'll check this, but not on christmas day! Merry Christmas!

**Comment by manny42** [comment]
It's done, the chunk download is functional! I'll be working on the interface to the plug on the next days

**Comment by k4nar** [comment]
Any issue with the Plug ?

**Comment by k4nar** [comment]
So, were are we ?

**Comment by k4nar** [comment]
I don't remember how we are detecting changes, but Dropbox just added webhooks : 
https://www.dropbox.com/developers/webhooks/tutorial

**Comment by k4nar** [comment]
Ok, so @Scylardor will be taking it from now.

I made a few changes, now the tests are launching, but are blocking at one point because the driver is imported in the test helper, thus a new Plug is created, trying to connect to Redis.

The code is really far behind develop, and a lot of stuff aren't working (for instance the root is never used). Also a new `DropboxDriver` is created in each handler, I wonder why.

**Comment by k4nar** [comment]
Oh also I don't think changes watching works. Apparently one can watch for changes either by getting a delta from a previous state, or by using webhooks. The former should be used during the start-up, and then hooks to monitor new changes.

**Comment by Scylardor** [comment]
I've taken care of the Dropbox driver and used the existing code base to rewrite it a bit like the S3 driver. I think all useful handlers are implemented, plus changes checking.

About OAuth authentication, I added a little script for the user to allow Onitu to use Dropbox. It generates the URL the user has to go to, and the generated OAuth tokens. These are what the user must use with Onitu, in order to let Onitu work without any further user interaction. These tokens seem to remain valid for a while, so that's good for me.

Webhooks can't be used since they need a web server (when using webhooks, Dropbox sends a POST request to the page with the changes).

To check changes, the most convenient way is currently to poll dropbox with `delta` commands to retrieve the changes between the last check. Dropbox uses a system of cursors to do it, which are pretty convenient — each time you do a `delta`, Dropbox sends a cursor for you to include in your next `delta` request to say "Hey, the last time I checked we were here. What's new ?", and avoid to reload all changes since the Dropbox creation; it returns only the changes that have occurred since this cursor.

I also checked that all is Python 2-3 compliant. The case-conflict issues apart (see #73 ), I didn't have problems when 'casually' using it, so I'm going to test it with tox.

I'm wondering about some minor issues, like:
- Should the Onitu application have a complete Dropbox access or an "app folder" access (an 'onitu' folder is created and the app isn't allowed to interact past this folder) to users' Dropbox ? If the 'folder' approach seems obviously connected to Onitu's root mechanism, allowing total access permits the user to be more flexible as to where / how he may want to use Onitu with his Dropbox.
- Dropbox emits two "recommandations": the first is for chunked uploads' chunk size, for which they recommand a minimum chunk size of 4 MB, and the second is time spacing between each `delta` request, which they advise to be "at least 5 minutes". Since it works perfectly well without respecting those, I wonder if we should enforce them (e.g. by using `set_chunk_size` and checking the timer amount) or don't care. At the moment, we don't care.

**Comment by k4nar** [comment]
Cool thanks !

For your first question, I think that we should try to get total access. The goal of Onitu is to manage and sync documents between places, so starting with an empty dir without access to the documents is not the way to go.

For the 4MB, I think that the best would be to set it in the manifest as a default. For the 5mn delta, I'm not sure. 5mn is quite long, so it would be bad for our reactivity. Maybe we could start with 1mn as a default.

**Comment by Scylardor** [comment]
Well I think we could set 4 MB as `set_chunk_size`.

About the driver's development, all tests pass, except the `test_move` one.

I've got a `TimeoutError` I have to investigate more. I wonder if it isn't related to the fact we currently cannot store the Onitu cursor in database.

Except the case issue we're almost done here. :)

**Comment by k4nar** [comment]
That's not the point of set_chunk_size. But I think we have an option to set the default chunk size. If not, it would be easy to do.

For test_move, does it pass with the last change ?

**Comment by Scylardor** [comment]
I'm up-to-date with develop.

Also, I finally have a TimeoutError on test_crash, on test_crash_rep2_to_rep1 (from Dropbox to Local storage). It is very odd since everything (in the logs) seems to be OK during the test, but once the transfers are done, the test just doesn't stop until it timeouts.

**Comment by k4nar** [comment]
Do you have the log ?

**Comment by Scylardor** [comment]
Ok, about `test_crash` I realized it was a stupid error when I analyzed the log (in the Dropbox → Local storage way, the root was prepended twice to the filename and so the filename was wrong).

I just ran tox and I confirm that `move_file` is the only test that doesn't pass. I'm going to take a good look at it tomorrow, but I don't know if it will be so easy to fix.

**Comment by k4nar** [comment]
That's great news ! Well, even without the move I think we can merge it. You should clean the code and the git history in order to create a pull-request. I'll review it in a few days or so.

**Comment by k4nar** [comment]
We can finally close this issue \o/ ! cf #75
