### ISSUE TITLE
Start S3 driver

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#31]
We should have a proof-of-concept for the S3 driver. It may not pass all the tests or fit all the requirements, but it should upload, download and watch changes.

**Comment by Scylardor** [comment]
I currently have a proof-of-concept driver working with Boto. Each S3 driver should fetch a user-defined S3 bucket.

It uploads, downloads and watches the changes of the Amazon S3 server. It is worth noting that since S3 hasn't a real watching system, it just polls the bucket contents and compare the timestamps with the Onitu database's ones at a fixed period of time to look for changes.

I'm going to do some minor changes (use multipart upload) before pushing the amazon_s3 branch. Then I shall see if the driver passes all the tests.

**Comment by Scylardor** [comment]
Seems like we've got a problem : Amazon S3 won't allow us to create multipart uploads with parts smaller than 5 MB (unless it is the only part).

We'll have to find a more convenient way to handle this kind of uploads. In the meantime, I keep the proof-of-concept "get the file contents as string, modify, send the modified string" version since it works fine (for small files at least).

**Comment by k4nar** [comment]
I'll add a handler `set_chunk_size`, which will take in parameter the requested size (ie: the one defined by the user or asked by Onitu) and return a valid one. S3 is not the only service to have this kind of behavior.

**Comment by k4nar** [comment]
In the meantime, we can close this issue as we have our PoC :) .
