### ISSUE TITLE
Finish S3 driver

### ISSUE THREAD

**Issue by k4nar** [onitu/onitu#46]
I don't see anything blocking in order to get S3 working, except #38.

**Comment by Scylardor** [comment]
Yes, there are a few improvements to be made, raise exceptions, implement the new changes, make tests. But that should be pretty quick.

There's still the #38 problem. Multipart upload is our only way to safely handle very large transfers. But even with this new handler, I'm not sure to understand how is it supposed to work on small transfers (less than 5 MB for Amazon). I think having an example would help.

**Comment by k4nar** [comment]
Well, you said that Amazon was accepting chunks < 5MB if it was the last chunk ? If the file is, let's say, of 20KB, you will have only one chunk, the last one. So you can request a 5MB chunk, you will only get 20KB, but S3 shouldn't complain about it.

**Comment by Scylardor** [comment]
That's it, `set_chunk_size` has resolved this problem.

Thus, the driver is nearly fully functional. The only remaining problem is that it doesn't pass all the tests. But since all the failed tests so far have only been timeout errors, I should retry with a longer timeout and a better Internet connection soon.

**Comment by k4nar** [comment]
You could also try to see what are the main bottlenecks. Maybe you do some useless operations, or we could use a better chunk size by default.

**Comment by Scylardor** [comment]
I'm glad to announce that with the latest commit, `amazon_s3` passes all the tests (with ONITU_TEST_TIME_UNIT=40 on my computer, but can probably pass with less) and can be deemed as fully functional (for now).

I still have some weird issues with tox on my computer, so I had to run the tests directly via py.test. Still trying to find out what's causing it.

**Comment by k4nar** [comment]
Can you make a Pull-Request ?

**Comment by Scylardor** [comment]
For the record, I've forked [tinys3](https://github.com/smore-inc/tinys3) in order to add multipart upload handling to it. I've made an issue on the original repo, but it seems pretty dead (last commit on Apr 30 and numerous unanswered issues), so I'm dealing with it myself.

Multipart uploads excluded, it seems to be a prety minimalistic solution (using requests) that works well. I think I'll ultimately replace `boto` by `tinys3`, since it is a lot lighter and fits our (simple) needs.
