### ISSUE TITLE
API file request problem

### ISSUE THREAD

**Issue by manny42** [onitu/onitu#76]
J'ai un bug avec le retrieve de la liste des fichiers.

Sur la requete /api/v1.0/files j'ai un :
`KeyNotFound: "Key 'files' not found in base"`

J'ai des fichiers dans les root des drivers, et ils sont bien detectes vu que ils se synchronisent dans les drivers.

**Comment by Scylardor** [comment]
I'm reproducing the problem.

It seems to come from a call to `escalator.get('files')`, which eventually raises the KeyError.

I'm investigating it but since I've no idea how we should retrieve all files metadatas, it would be faster if @k4nar had some input on it. Maybe @Khady will be able to help too.

Retrieving a particular file metadata is working, so I guess it shouldn't be too hard to fix.

**Comment by k4nar** [comment]
Each file is stored in the db with the key `file:{fid}`. In order to get all the files in the db, the easiest way is to use a Range request with the prefix `file:` : 

``` python
for key, value in escalator.range('file:'):
    ...
```

**Comment by k4nar** [comment]
I have some things to refactor in the API and the Metadata, I'll push a fix soon.
