### ISSUE TITLE
API method request and modification

### ISSUE THREAD

**Issue by manny42** [onitu/onitu#78]
I am opening this issue to have a place to suggest and ask for modifications on the Onitu's API.

I will start by some requests:
- Is it possible to return array rather that { "entries" : [...] } (same for files, etc...) on the general GETs, this is to be compatible with restangular, if it's not hard to do.
- Is it possible to add a description field to the drivers and a method to modify it (PUT) ?
- Is it possible to add and delete drivers directly from the web interface or is it just not wanted? If it can be done, is it possible to add method to do it on the API?

**Comment by k4nar** [comment]
- No, unfortunately it's not possible due to that particular vulnerability: http://haacked.com/archive/2009/06/25/json-hijacking.aspx. Anyway, you just have to use `data['files']` instead of `data` so it's not a big deal.
- Well, drivers do have a description, which is in their manifest. I don't think that we have any route to access it from the API, but there should be one. This information is in a file and thus is not editable. Adding a description to entries is not really interesting I think, as they are defined by the user himself.
- Yes, we should be able to edit the entries from the API. But I think it would be better to wait for the new rules before implementing it.
